// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("prometheus")
	ScopeName = "github.com/pkcll/opentelemetry-collector-contrib/receiver/prometheusreceiver"
)

const (
	MetricsStability = component.StabilityLevelBeta
)
